#!/bin/bash

set -xe

SCRIPT_PATH=$(cd "$(dirname "$0")" && pwd)
PY_VERSION=$(python --version | sed 's/\s\+/-/g')

black --diff --check ${SCRIPT_PATH}/gke_logging
ruff check
mypy ${SCRIPT_PATH}/gke_logging

poetry install -E asgi
poetry run pytest tests
